export enum Unit {
  Piece = 'piece',
  Gram = 'gram',
  Kilogram = 'kilogram',
  Cup = 'cup',
  TableSpoon = 'tbsp',
  TeaSpoon = 'tsp',
  Centimeter = 'cm',
  Milliliter = 'ml',
  Liter = 'l',
  Package = 'package',
  ToTaste = 'to taste',
  Pinch = 'pinch',
  Handful = 'handful',
  Serving = 'serving',
}
